// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

#include "cangjie/CHIR/Optimization/ExternSequenceMerge.h"

#include "cangjie/CHIR/Analysis/Utils.h"
#include "cangjie/CHIR/Utils/CHIRCasting.h"
#include "cangjie/CHIR/Utils/Utils.h"
#include "cangjie/CHIR/Utils/Visitor/Visitor.h"
#include "cangjie/Utils/ConstantsUtils.h"

#include <iostream>

namespace Cangjie::CHIR {
namespace {
const std::string EVAL_FUNC = "eval";
const std::string EXTERN_SEQUENCE_CTOR = "ExternSequence";

/**
 * If @p expr is an evaluation T.eval(tree) generated by the desugaring of an Extern operation, return it. Unlike the
 * calls to eval in the source code, its result is marked EXTERN_EVAL (see Translator::Visit(const AST::CallExpr&)).
 */
ApplyBase* AsGeneratedEval(Expression& expr)
{
    if (expr.GetExprKind() != ExprKind::APPLY && expr.GetExprKind() != ExprKind::TRY_APPLY) {
        return nullptr;
    }
    auto apply = StaticCast<ApplyBase*>(&expr);
    auto result = apply->GetResult();
    if (!result || !result->TestAttr(Attribute::EXTERN_EVAL) ||
        !IsExpectedCustomType(*result->GetType(), CORE_PACKAGE_NAME, STD_LIB_EXTERN)) {
        return nullptr;
    }
    auto args = apply->GetArgs();
    if (args.size() != 1 || args[0]->GetType() != result->GetType() ||
        apply->GetCallee()->GetSrcCodeIdentifier() != EVAL_FUNC) {
        return nullptr;
    }
    return apply;
}

/**
 * Whether @p expr may be evaluated before an evaluation instead of after it: it neither throws nor accesses memory,
 * which the foreign runtime may modify, e.g. by calling back into Cangjie. These are the expressions that build trees.
 */
bool CanEvaluateEarlier(const Expression& expr)
{
    switch (expr.GetExprKind()) {
        case ExprKind::CONSTANT:
        case ExprKind::TUPLE:
        case ExprKind::FIELD:
        case ExprKind::BOX:
        case ExprKind::DEBUGEXPR:
            return true;
        default:
            return false;
    }
}
} // namespace

ExternSequenceMerge::ExternSequenceMerge(CHIRBuilder& builder, bool isDebug) : builder(builder), isDebug(isDebug)
{
}

void ExternSequenceMerge::RunOnPackage(const Package& package)
{
    for (auto func : package.GetGlobalFuncsWithBody()) {
        RunOnFunc(*func);
    }
}

void ExternSequenceMerge::RunOnFunc(const Function& func)
{
    std::vector<Block*> blocks;
    Visitor::Visit(func, [&blocks](Block& block) {
        blocks.emplace_back(&block);
        return VisitResult::CONTINUE;
    });
    for (auto block : blocks) {
        for (auto expr : block->GetExpressions()) {
            // Skip the evaluations already merged into a later one.
            if (expr->GetParentBlock() == nullptr) {
                continue;
            }
            auto first = AsGeneratedEval(*expr);
            while (first && first->GetResult()->GetUsers().empty()) {
                auto externTy = StaticCast<EnumType*>(first->GetResult()->GetType());
                auto sequenceIndex = GetSequenceIndex(*externTy->GetEnumDef());
                auto second = sequenceIndex ? FindNextEval(*first) : nullptr;
                if (!second) {
                    break;
                }
                Merge(*first, *second, *sequenceIndex);
                first = second;
            }
        }
    }
}

/**
 * The generated evaluation that follows @p eval, if only expressions that CanEvaluateEarlier are in between. When
 * @p eval is in a try block, the next one must be the terminator of its success block, with the same error block.
 */
ApplyBase* ExternSequenceMerge::FindNextEval(const ApplyBase& eval)
{
    std::vector<Expression*> exprs;
    size_t start = 0;
    if (eval.GetExprKind() == ExprKind::TRY_APPLY) {
        auto successBlock = StaticCast<const TryApply&>(eval).GetSuccessBlock();
        // The tree of the first evaluation must be available in the block of the second one.
        if (successBlock->GetPredecessors().size() != 1) {
            return nullptr;
        }
        exprs = successBlock->GetExpressions();
    } else {
        exprs = eval.GetParentBlock()->GetExpressions();
        auto it = std::find(exprs.begin(), exprs.end(), &eval);
        CJC_ASSERT(it != exprs.end());
        start = static_cast<size_t>(std::distance(exprs.begin(), it)) + 1;
    }
    for (size_t i = start; i < exprs.size(); ++i) {
        if (auto next = AsGeneratedEval(*exprs[i])) {
            if (next->GetExprKind() != eval.GetExprKind() ||
                next->GetResult()->GetType() != eval.GetResult()->GetType()) {
                return nullptr;
            }
            // An exception raised by the first evaluation must reach the same handler.
            if (next->GetExprKind() == ExprKind::TRY_APPLY &&
                StaticCast<TryApply*>(next)->GetErrorBlock() != StaticCast<const TryApply&>(eval).GetErrorBlock()) {
                return nullptr;
            }
            return next;
        }
        if (!CanEvaluateEarlier(*exprs[i])) {
            return nullptr;
        }
    }
    return nullptr;
}

/**
 * Change from:
 *     %r1 = Apply(T.eval, %e1)      // %r1 unused
 *     ...
 *     %r2 = Apply(T.eval, %e2)
 * to:
 *     ...
 *     %s = Tuple(<index of ExternSequence>, Box(%e1), Box(%e2))
 *     %r2 = Apply(T.eval, %s)
 * When the evaluations are TryApply, the first one is replaced by a GoTo to its success block.
 */
void ExternSequenceMerge::Merge(ApplyBase& first, ApplyBase& second, size_t sequenceIndex)
{
    auto parent = second.GetParentBlock();
    const auto& loc = second.GetDebugLocation();
    auto externTy = second.GetResult()->GetType();
    auto e1 = first.GetArgs()[0];
    auto e2 = second.GetArgs()[0];
    // The arguments of type Extern<T> are recursive, so they are boxed (see BoxRecursionValueType).
    auto boxTy = builder.GetType<RefType>(builder.GetType<BoxType>(externTy));
    auto selector = builder.CreateConstantExpression<IntLiteral>(
        loc, builder.GetUInt32Ty(), parent, static_cast<uint64_t>(sequenceIndex));
    auto box1 = builder.CreateExpression<Box>(loc, boxTy, e1, parent);
    auto box2 = builder.CreateExpression<Box>(loc, boxTy, e2, parent);
    auto sequence = builder.CreateExpression<Tuple>(loc, externTy,
        std::vector<Value*>{selector->GetResult(), box1->GetResult(), box2->GetResult()}, parent);
    for (Expression* expr : std::initializer_list<Expression*>{selector, box1, box2, sequence}) {
        expr->MoveBefore(&second);
    }
    second.ReplaceOperand(e2, sequence->GetResult());

    if (isDebug) {
        std::cout << "[ExternSequenceMerge] The evaluation" + ToPosInfo(first.GetDebugLocation()) +
                " has been merged into the evaluation" + ToPosInfo(loc) + ".\n";
    }
    auto firstBlock = first.GetParentBlock();
    if (first.GetExprKind() == ExprKind::TRY_APPLY) {
        auto successBlock = StaticCast<TryApply&>(first).GetSuccessBlock();
        auto firstLoc = first.GetDebugLocation();
        first.RemoveSelfFromBlock();
        firstBlock->AppendExpression(builder.CreateTerminator<GoTo>(firstLoc, successBlock, firstBlock));
    } else {
        first.RemoveSelfFromBlock();
    }
}

/** The index of the constructor ExternSequence in @p externDef, if the standard library defines it. */
std::optional<size_t> ExternSequenceMerge::GetSequenceIndex(const EnumDef& externDef)
{
    if (auto it = sequenceIndices.find(&externDef); it != sequenceIndices.end()) {
        return it->second;
    }
    CJC_ASSERT(GetSelectorType(externDef) == Type::TypeKind::TYPE_UINT32);
    std::optional<size_t> index;
    auto ctors = externDef.GetCtors();
    for (size_t i = 0; i < ctors.size(); ++i) {
        if (ctors[i].name == EXTERN_SEQUENCE_CTOR) {
            index = i;
            break;
        }
    }
    sequenceIndices.emplace(&externDef, index);
    return index;
}
} // namespace Cangjie::CHIR
