// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

#ifndef CANGJIE_CHIR_OPTIMIZATION_EXTERN_SEQUENCE_MERGE_H
#define CANGJIE_CHIR_OPTIMIZATION_EXTERN_SEQUENCE_MERGE_H

#include "cangjie/CHIR/IR/CHIRBuilder.h"
#include "cangjie/CHIR/IR/Expression/Terminator.h"
#include "cangjie/CHIR/IR/Package.h"

#include <optional>
#include <unordered_map>

namespace Cangjie::CHIR {
/**
 * CHIR Opt Pass (--enable-extern-sequence): merge consecutive evaluations of Extern operations
 *     T.eval(E1)
 *     T.eval(E2)
 * whose first result is unused into one evaluation
 *     T.eval(ExternSequence(E1, E2))
 * Only the evaluations generated by the desugaring of Extern operations are merged, and only when the expressions
 * between them can be evaluated before the first evaluation.
 */
class ExternSequenceMerge {
public:
    ExternSequenceMerge(CHIRBuilder& builder, bool isDebug);

    void RunOnPackage(const Package& package);

private:
    void RunOnFunc(const Function& func);
    ApplyBase* FindNextEval(const ApplyBase& eval);
    void Merge(ApplyBase& first, ApplyBase& second, size_t sequenceIndex);
    std::optional<size_t> GetSequenceIndex(const EnumDef& externDef);

    CHIRBuilder& builder;
    bool isDebug{false};
    std::unordered_map<const EnumDef*, std::optional<size_t>> sequenceIndices;
};
} // namespace Cangjie::CHIR

#endif
